# Generated by Django 4.1.6 on 2023-02-10 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_type', models.CharField(choices=[('ins', 'Моментальный'), ('pre', 'Предзаказ')], max_length=3)),
                ('location', models.CharField(max_length=150)),
                ('location_more_info', models.CharField(blank=True, max_length=150, null=True)),
                ('location_type', models.CharField(blank=True, max_length=150, null=True)),
                ('count', models.FloatField()),
                ('btc_price', models.FloatField()),
                ('units', models.CharField(default='г', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('preview_text', models.TextField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='')),
                ('big_photo', models.ImageField(null=True, upload_to='')),
                ('deals_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=130)),
                ('type_of_product', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('locations', models.ManyToManyField(to='kraken.itemlocation')),
                ('photos', models.ManyToManyField(to='kraken.productphoto')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kraken.shop')),
            ],
        ),
        migrations.CreateModel(
            name='InfoText',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kraken.infocategory')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150)),
                ('published', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('star_count', models.IntegerField()),
                ('image', models.ImageField(default='default_avatar2.jpeg', upload_to='')),
                ('product', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='kraken.product')),
                ('shop', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='kraken.shop')),
            ],
        ),
    ]
