# Generated by Django 4.1.6 on 2023-02-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('slug', models.SlugField(default='rule', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='other_pages',
            field=models.ManyToManyField(to='kraken.page'),
        ),
    ]
