# Generated by Django 4.1.6 on 2023-02-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0003_captcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('image', models.ImageField(default='default_avatar2.jpeg', upload_to='')),
            ],
        ),
    ]
