# Generated by Django 4.1.6 on 2023-03-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0005_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='city_selected',
            field=models.ForeignKey(default='11f5916f-5293-443a-9fbf-faa7f36069e7', on_delete=django.db.models.deletion.CASCADE, to='kraken.city'),
        ),
    ]
