# Generated by Django 4.1.6 on 2023-03-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0008_exchange_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='card',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
