# Generated by Django 4.1.6 on 2023-03-22 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0010_exchangeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeinfo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
