# Generated by Django 4.1.6 on 2023-03-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0011_alter_exchangeinfo_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlocation',
            name='btc_price',
        ),
        migrations.RemoveField(
            model_name='itemlocation',
            name='units',
        ),
        migrations.AddField(
            model_name='itemlocation',
            name='rub_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemlocation',
            name='count',
            field=models.CharField(max_length=30),
        ),
    ]
