# Generated by Django 4.1.6 on 2023-03-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0012_remove_itemlocation_btc_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
