# Generated by Django 4.1.6 on 2023-03-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0013_alter_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='locations',
            field=models.ManyToManyField(editable=False, to='kraken.itemlocation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(editable=False, to='kraken.productphoto'),
        ),
    ]
