# Generated by Django 4.1.6 on 2023-03-25 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0014_alter_product_locations_alter_product_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
