# Generated by Django 4.2.4 on 2023-08-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0015_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='deals_count',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
