# Generated by Django 4.2.4 on 2023-08-14 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0016_alter_shop_deals_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержание тикета')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kraken.shop')),
            ],
        ),
    ]
