# Generated by Django 4.2.5 on 2023-09-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0018_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
