# Generated by Django 4.2.5 on 2023-09-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kraken', '0020_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='content',
        ),
        migrations.AddField(
            model_name='ticket',
            name='messages',
            field=models.ManyToManyField(to='kraken.message'),
        ),
    ]
