from django.urls import path
from .views import *

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('news/', NewsList.as_view(), name='news'),
    path('news/<uuid:uuid>/', NewsDetail.as_view()),
    path('text/<slug:name>/', InfoTextView.as_view()),
    path('status/get', jquery_get),
    path('catalog/', CatalogView.as_view()),
    path('shop/catalog/<uuid:uuid>/', ShopCatalogDetail.as_view()),
    path('shop/item/<uuid:uuid>/', ShopItem.as_view()),
    path('shop/comments/<uuid:uuid>/', CommentsView.as_view()),
    path('shop/vacancies/<uuid:uuid>/', VacanciesView.as_view()),
    path('shop/page/<uuid:uuid>/<slug:slug>/', OtherPageView.as_view()),
    path('entry/login/', AuthView.as_view(), name='login'),
    path('entry/post/login', LoginView.as_view()),
    path('entry/post/register', RegisterView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('select/city/', SelectCityView.as_view(), name='select_city'),
    path('profile/finances/', FinancesView.as_view()),
    path('profile/orders/', OrdersView.as_view()),
    path('notifications/', NotificationsView.as_view()),
    path('deposit-coupons/', CouponsView.as_view()),
    path('select/', SelectPostView.as_view(), name='select_city_post'),
    path('profile/preferences/', ProfileSettings.as_view(), name='preferences'),
    path('profile/update/avatar/', ProfileUpdatePhoto.as_view()),
    path('profile/update/password/', ProfilePasswordChange.as_view()),
    path('profile/logout/', logout_request),
    path('ticket/admin/', TicketAdmin.as_view()),
    path('exchange/my-orders/', ExchangeOrders.as_view()),
    path('exchange/', ExchangeView.as_view()),
    path('exchange/<uuid:uuid>/', ExchangeDetail.as_view()),
    path('exchange/<uuid:uuid>/create/', ExchangeCreateView.as_view()),
    path('exchange/<uuid:exchange>/order/<uuid:order>', ExchangeInfoView.as_view(), name='exchange_info'),
    path('chat/', ChatView.as_view(), name='chat'),
    path('catalog/<slug:slug>/', CatalogView.as_view()),
    path('catalog/<slug:slug>/<slug:slug1>/', CatalogView.as_view()),
    path('ticket/shop/<slug:slug>/', CreateTicketShop.as_view()),
    path('check/', CaptchaStart.as_view(), name='check'),
    path('check_captcha', check_captcha),
    path('chat/<uuid:uuid>/', ChatDetail.as_view()),
    path('chat/<uuid:ticket_uuid>/send', create_message),
]
